#!/bin/bash

# Beaker installation and extension
beakerx install
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install beakerx-jupyterlab

# Git Jupyter Lab extension 
jupyter labextension install @jupyterlab/git
jupyter serverextension enable --py jupyterlab_git

# Github Jupyter Lab extension
jupyter labextension install @jupyterlab/github

# Draw.io Jupyter Lab extension
jupyter labextension install jupyterlab-drawio

# Rise Jupyter extension (presentation mode)
jupyter-nbextension install rise --py --sys-prefix
jupyter-nbextension enable  rise --py --sys-prefix
jupyter labextension install jupyterlab_rise

# Plotly Jupyter Lab extension
jupyter labextension install @jupyterlab/plotly-extension

# Table of contents Jupyter Lab Extension
jupyter labextension install @jupyterlab/toc

# Building everything
jupyter lab build
jupyter labextension update --all


rm conda-bld -R
